### ISSUE TITLE
Dark Mode on ReadTheDocs should automatically activate based on OS preferences

### ISSUE THREAD

**Issue by moinnadeem** [mosaicml/composer#754] opened 2022-03-15 03:07 UTC
The ReadTheDocs page goes into dark mode based off of a button, but it should follow OS preferences when available.

**Comment by hanlint** [comment] 2022-03-22 00:32
I was unable to reproduce this issue -- I switched my macOS settings, and when creating an incognito window, `docs.mosaicml.com` loaded either dark or light.

Unlike github.com however, your the mode does persist when you change in the settings. Since this is an edge case (e.g. switching from light -> dark while having the page open), going to close this issue.

**Closed by hanlint** 2022-03-22 00:32 UTC
Labels: documentation
