### ISSUE TITLE
Synthetic data has slower throughput than imagenet

### ISSUE THREAD

**Issue by growlix** [mosaicml/composer#148] opened 2021-12-11 00:58 UTC
** Environment **
- Hardware (GPU, or instance type): 8x COTA 3080

** To reproduce

Compare running with `composer/yamls/models/resnet50_synthetic.yaml` to `composer/yamls/models/resnet50.yaml`. See W&B runs [here](https://wandb.ai/mosaic-ml/matthew-test/reports/Throughput-Regression-on-3080-w-progressive-resizing--VmlldzoxMzI3NDgy).

## Expected behavior

Using synthetic data should be at least as fast, if not faster than using actual data. Issue is _slightly_ improved by increasing `train_dataset.synthetic.total_dataset_size: 12288` to something larger (e.g. 100000).

**Comment by ravi-mosaicml** [comment] 2021-12-13 22:59
I re-ran an experiment using a newer docker image and the latest `dev` branch of composer. Specifically:
* Base Dockerfile: https://github.com/mosaicml/composer/blob/938ac0028c8622d5c59d8a3c470c85a326b8b6ee/docker/pytorch/Dockerfile
* Docker image: https://hub.docker.com/layers/mosaicml/pytorch/1.9.1_cu111-python3.8-ubuntu20.04/images/sha256-d0f3c9a101f38d01b4b468e77b42d95c4490364302b750e5ee3f7e7ccb365c86?context=repo
* WandB proejct: https://wandb.ai/mosaic-ml/ravi_resnet50_matt_regression?workspace=user-ravimosaicml

Both Synthetic Data and Real data got around 4900 img / second.

I suppose this regression was caused by:
* Some dockerfile misconfiguration (similar to the pillow simd dependnecy)
* Some bad synthetic dataset configuration (which has since been changed between what is on `main` and the latest which is on `dev`)

Closing this issue as it will go away with the next release of composer.

**Closed by ravi-mosaicml** 2021-12-13 22:59 UTC
Labels: bug
