### ISSUE TITLE
Validate that `dataloader._iterator` is `None`

### ISSUE THREAD

**Issue by ravi-mosaicml** [mosaicml/composer#313] opened 2022-01-31 22:25 UTC
I am very skeptical that the algorithms that use `add_dataset_transform` in `composer.utils.data` work as intended, as the dataloader workers are already created before the INIT event runs (and the algorithms attempt to monkeypatch the dataset). Instead, `add_dataset_transform` should be replaced by modifying the data on the `AFTER_DATALOADER` event. This will require that `composer.utils.augmentation_primiatves` are reimplemented to operate on batches of images (rather than on individual PIL images), and likely switch to using `torchvision` instead of PIL

It would be good to run a test to confirm that randaugment, augmix, and colout do not work as intentend.

**Comment by hanlint** [comment] 2022-01-31 22:31
🤔 cc: @coryMosaicML @growlix 

I dont think the proposed solution would work, as the `AFTER_DATALOADER` event now runs on GPU. We've been using `add_dataset_transform` since launch, so unless something broke, it was working previously.

**Comment by growlix** [comment] 2022-01-31 22:48
I think things are working fine on `main`, but going to look into this on `dev` now. @hanlint is correct that this would require doing augmentations on GPU.

**Comment by growlix** [comment] 2022-01-31 23:54
Testing this made me aware that `randaugment` and `augmix` don't work with our CIFAR10 dataset, but not for the reason that @ravi-mosaicml mentioned. It's because the the `cifar10` dataset already has `to_tensor()` in the list of transformations, and `add_dataset_transform()` just appends `randaugment`, so it ends up acting on tensor. About to test w/ ImageNet.

**Comment by growlix** [comment] 2022-02-01 00:09
Seems to work on ImageNet for `main` and `dev`. Going to update `add_dataset_transform()` to be cifar10-friendly.

**Comment by hanlint** [comment] 2022-02-01 00:11
Should we support a 
```
add_dataset_transform(.., before_to_tensor=True)
```
option?

**Comment by hanlint** [comment] 2022-02-01 00:18
@ravi-mosaicml OK with closing this issue then? the CIFAR-10 issue is a different issue.

**Comment by growlix** [comment] 2022-02-01 00:31
Good to close, cifar10 compatibility PR incoming!

**Comment by ravi-mosaicml** [comment] 2022-02-01 00:41
@growlix can you elaborate how you confirmed this?

**Comment by ravi-mosaicml** [comment] 2022-02-01 02:41
Ah, since pytorch dataloader lazily forks on the first iteration, this works. However, I would not like to assume this will always be the case, as there is no guarantee that a user didn't already spin their dataloader before passing it into the trainer.

If we would like to do CPU data augmentations as a first-class API, then I think our trainer init should take the (dataset, batch size, sampler, drop_last) rather than a dataloader. We can then construct the dataloader at the appropriate time.

**Comment by growlix** [comment] 2022-02-01 18:46
I confirmed by running `run_mosaic_trainer.py -f {resnet50, resnet56} --algorithms randaugment --dataloader.num_workers 8` on a cota-g1-3080 interactive instance for `dev` and `main` and set a breakpoint in [`algorithms/randaugment/randaugment.py`](https://github.com/mosaicml/composer/blob/fa1b992c213094f63ca3b860aaf06e2ea1c82d88/composer/algorithms/randaugment/randaugment.py#L42) and checking that `randaugment()` was executing and the tensor was being modified.

**Comment by growlix** [comment] 2022-02-01 18:46
Is there a fix that would accommodate the scenario you're describing? (pre-spun, persistent workers, n workers > 0)

**Comment by ravi-mosaicml** [comment] 2022-02-01 21:33
The easiest 'fix' would be to recreate the dataloader e.g. something like `dataloader = Dataloader(**vars(dataloader))`, but I am not a fan of this approach since this wouldn't support a user's custom dataloader.

**Comment by hanlint** [comment] 2022-02-01 21:42
Yeah, agree i think the edge case can be not supported.

**Closed** 2022-02-02 01:22 UTC
Labels: bug
