### ISSUE TITLE
`Not all values in concat_tokens dict have same len()` error when loading c4

### ISSUE THREAD

**Issue by rabeeh-karimi** [mosaicml/composer#1670] opened 2022-10-24 16:57 UTC
** Environment **
```
Collecting system information...
---------------------------------
System Environment Report        
Created: 2022-10-24 09:56:06 PDT
---------------------------------

PyTorch information
-------------------
PyTorch version: 1.12.1
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.9.13 (main, Aug 25 2022, 23:26:10)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-92-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: NVIDIA RTX A6000
GPU 1: NVIDIA RTX A6000
GPU 2: NVIDIA RTX A6000
GPU 3: NVIDIA RTX A6000

Nvidia driver version: 495.29.05
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] ema-pytorch==0.0.10
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.4
[pip3] pytorch-ranger==0.1.1
[pip3] torch==1.12.1
[pip3] torch-optimizer==0.3.0
[pip3] torchaudio==0.12.1
[pip3] torchmetrics==0.7.3
[pip3] torchvision==0.13.1
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.3.1               h2bc3f7f_2  
[conda] ema-pytorch               0.0.10                   pypi_0    pypi
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py39h7f8727e_0  
[conda] mkl_fft                   1.3.1            py39hd3c417c_0  
[conda] mkl_random                1.2.2            py39h51133e4_0  
[conda] numpy                     1.22.4                   pypi_0    pypi
[conda] pytorch                   1.12.1          py3.9_cuda11.3_cudnn8.3.2_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] pytorch-ranger            0.1.1                    pypi_0    pypi
[conda] torch                     1.12.1                   pypi_0    pypi
[conda] torch-optimizer           0.3.0                    pypi_0    pypi
[conda] torchaudio                0.12.1               py39_cu113    pytorch
[conda] torchmetrics              0.7.3                    pypi_0    pypi
[conda] torchvision               0.13.1                   pypi_0    pypi


Composer information
--------------------
Composer version: 0.10.1
Composer commit hash: None
Host processor model name: AMD EPYC 7502 32-Core Processor
Host processor core count: 64
Number of nodes: 1
Accelerator model name: NVIDIA RTX A6000
Accelerators per node: 1
CUDA Device Count: 4
```

** To reproduce

please run:
```
import composer
  
split = "train"
num_samples = 10
tokenizer_name = "bert-base-uncased"
max_seq_len = 512
group_method = "concat"
data = composer.datasets.C4Dataset(split, num_samples, tokenizer_name, max_seq_len, group_method, shuffle=False, shuffle_buffer_size=10000, seed=5)
print(data)

for x in data:
    print(x)
```

## Error
```
When using group_method 'concat', sequential token samples are concatenated and chunked into fixed-length samples of size max_seq_len=512. In general we cannot detect ahead-of-time if your setting of num_samples=10 will be larger than the original dataset, but if it is larger, the original dataset will cycle until the new nominal length of 10.
<composer.datasets.c4.C4Dataset object at 0x7f3b7dae1be0>
Token indices sequence length is longer than the specified maximum sequence length for this model (2533 > 512). Running this sequence through the model will result in indexing errors
Traceback (most recent call last):
  File "/net/nfs.cirrascale/s2-research/rabeehk/diffusion/sample.py", line 11, in <module>
    for x in data:
  File "/net/nfs.cirrascale/s2-research/rabeehk/conda/envs/success/lib/python3.9/site-packages/datasets/iterable_dataset.py", line 723, in __iter__
    for key, example in self._iter():
  File "/net/nfs.cirrascale/s2-research/rabeehk/conda/envs/success/lib/python3.9/site-packages/datasets/iterable_dataset.py", line 713, in _iter
    yield from ex_iterable
  File "/net/nfs.cirrascale/s2-research/rabeehk/conda/envs/success/lib/python3.9/site-packages/datasets/iterable_dataset.py", line 589, in __iter__
    yield from islice(self.ex_iterable, self.n)
  File "/net/nfs.cirrascale/s2-research/rabeehk/conda/envs/success/lib/python3.9/site-packages/composer/datasets/c4.py", line 274, in __iter__
    yield from cycle(self.ex_iterable)
  File "/net/nfs.cirrascale/s2-research/rabeehk/conda/envs/success/lib/python3.9/site-packages/datasets/iterable_dataset.py", line 368, in __iter__
    transformed_batch.update(self.function(*function_args, **self.fn_kwargs))
  File "/net/nfs.cirrascale/s2-research/rabeehk/conda/envs/success/lib/python3.9/site-packages/composer/datasets/c4.py", line 370, in _group_tokens
    raise ValueError('Not all values in concat_tokens dict have same len()')
ValueError: Not all values in concat_tokens dict have same len()
```
## Expected behavior
loading c4

**Comment by mvpatel2000** [comment] 2022-10-25 18:03
Hm... I'm having trouble reproducing this. I ran the minimal example given and it seems to work:
```
When using group_method 'concat', sequential token samples are concatenated and chunked into fixed-length samples of size max_seq_len=512. In general we cannot detect ahead-of-time if your setting of num_samples=10 will be larger than the original dataset, but if it is larger, the original dataset will cycle until the new nominal length of 10.
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 455k/455k [00:00<00:00, 1.26MB/s]
<composer.datasets.c4.C4Dataset object at 0x10078c0d0>
Token indices sequence length is longer than the specified maximum sequence length for this model (2533 > 512). Running this sequence through the model will result in indexing errors
{'attention_mask': 
# data continues here
```

**Comment by mvpatel2000** [comment] 2022-10-25 18:09
@rabeeh-karimi can you verify the version of `datasets` is compatible with what is described in `setup.py`? It could be some kind of dependency incompatability.

In either case, highly recommend using streaming datasets instead! It's much better :)

**Comment by mvpatel2000** [comment] 2022-11-21 22:18
@rabeeh-karimi Will be closing out this issue since there was no followup. Please feel free to reach out if this is still an existing issue and we can reopen. 

As mentioned by Bandish, in the future we recommend looking at our new streaming implementation. We will be trying to move datasets outside of Composer as much as possible so it stays focused on its core -- training!

**Closed by mvpatel2000** 2022-11-21 22:18 UTC
Labels: bug
